ALTER TABLE "Service" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'Outros';
ALTER TABLE "Service" ADD COLUMN "color" TEXT NOT NULL DEFAULT '#7a2638';
ALTER TABLE "Service" ADD COLUMN "archivedAt" TIMESTAMP(3);
